name: billiard_aim_tool
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_overlay_window: ^0.5.0
  permission_handler: ^12.0.0+1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.1
  flutter_addons: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.8
  custom_lint: ^0.5.11
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true



